hello_hello:
    resource: "@HelloHelloBundle/Resources/config/routing.yml"
    prefix:   /

acme_task_bundle:
    resource: "@AcmeTaskBundle/Resources/config/routing.yml"
    prefix: /

home_store:
    resource: "@HomeStoreBundle/Resources/config/routing.yml"
    prefix:   /
    
home_user:
    resource: "@HomeUserBundle/Resources/config/routing.yml"
    prefix:   /

blog: 
  path: /blog/{page}
  defaults: {_controller: HomeBlogBundle:Blog:index, page: 1}
  requirements:
        page: \d+

blog_show:
   path: /blog/{slug}
   defaults: {_controller: HomeBlogBundle:Blog:estudo}

article_show:
   path: /articles/{culture}/{year}/{title}.{_format}
   defaults: {_controller: HomeBlogBundle:Article:show, _format: html}
   requirements:
      culture: en|fr
      _format: html|rss
      year: \d+



